### PR TITLE
Set github_branch to trunk

### LINKED ISSUE #33: "Edit this page" on Documentation gets a 404 error
**Describe the bug**
The "Edit this page" on Documentation gets a 404 error. This is caused by a configuration for the "docs" template to point to "master", needs to be changed to "trunk" 

**To Reproduce**
1. First I navigate to and page that uses the "docs"template (e.g. Documentation).
2. Then I click on "Edit this page" on the right side of the page/
3. And then we get a 404 error because it is looking for the "master" branch and we use "trunk"

**Expected behavior**
The correct pages is found and the developer should be prompted to fork and submit changes...

**Screenshots**
Screen Shot 2021-05-20 at 7 28 43 PM

**Smartphone (please complete the following information):**
 - Device: MacBook Pro (15-inch, 2018)
 - OS: MacOS 11.3.1 (20E241)
 - Browser: Chrome
 - Version 90.0.4430.212 (Official Build) (x86_64)

**Were you using an @application when the bug was found?**
  - No

**Additional context**

### PR DESCRIPTION
**Pull request by cpswan**
Fixes #33 

**- What I did**

Searched Docsy theme for `master`, and found `github_branch` setting need to be changed.

**- How I did it**

Set `github_branch= "trunk"` in `config.toml` 

**- How to verify it**

Browse to docs and click on "Edit this page"

**- Description for the changelog**

Set github_branch to trunk

### CODE REVIEW

**Comment by nickelskevin** [comment]
Thank you - was expecting to have to do this today and you beat me to it!

**Review by nickelskevin — COMMENTED** [review]
Purrrfect, thank you

**Comment by cpswan** [comment]
Looks like this was closed without merging :/

**Review by nickelskevin — APPROVED** [review]
Oops, sorry for the redux

**Pull request merged**
