### PR TITLE
Updated the baseURL in the config.toml file

### PR DESCRIPTION
**Pull request by anthonyvprakash**
**- What I did**
Updated the BaseURL or Docsy
**- How I did it**
Updated it in the config.toml file
**- How to verify it**
Verify the SEO tags
**- Description for the changelog**

### CODE REVIEW

**Review by cpswan — COMMENTED** [review]
What's the motivation for making this change?

I think it may make the staging site less useful, as all the staging links will take us to prod.

"If it ain't broke, then don't try to fix it", so what's broke that's fixed by this?

**Comment by anthonyvprakash** [comment]
@cpswan the main reason for the change is for fixing the links from an SEO standpoint 

Right now if you look at the og:image tags(built by head.html) in the source they come up as /landing_page/logo.sch


So when you share the link somewhere there is no thumbnail image that shows up - that's what is broke 😀

Trying this after spending a lot of time with Hugo documents over the last 24 hrs.

**Comment by cpswan** [comment]
@anthonyvprakash how about if we instead modified config.toml as part of the release process?

We could then have the full devstaging.atsign.wtf in the config.toml for this repo, and rewrite that to atsign.dev when we do a release.

**Comment by anthonyvprakash** [comment]
@cpswan  sure - that will be a learning for me :)

**Comment by cpswan** [comment]
@anthonyvprakash I'll close this PR and open a separate one with the changes we need to make to work across staging and prod.

**Pull request closed without merging**
